// <auto-generated />
using System;
using FoodMate.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FoodMate.Infrastructure.Data.Migrations
{
    [DbContext(typeof(FoodMateDbContext))]
    partial class FoodMateDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FoodMate.Core.Entities.AiRecognitionLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("CompletionTokens")
                        .HasColumnType("integer")
                        .HasColumnName("completion_tokens");

                    b.Property<string>("CorrectedResult")
                        .HasColumnType("text")
                        .HasColumnName("corrected_result");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("error_message");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsCorrected")
                        .HasColumnType("boolean")
                        .HasColumnName("is_corrected");

                    b.Property<int>("LatencyMs")
                        .HasColumnType("integer")
                        .HasColumnName("latency_ms");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("model_name");

                    b.Property<string>("ParsedResult")
                        .HasColumnType("text")
                        .HasColumnName("parsed_result");

                    b.Property<int?>("PromptTokens")
                        .HasColumnType("integer")
                        .HasColumnName("prompt_tokens");

                    b.Property<string>("RawResponse")
                        .HasColumnType("text")
                        .HasColumnName("raw_response");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("ix_ai_logs_corrected")
                        .HasFilter("is_corrected");

                    b.HasIndex("Status", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_ai_logs_status_created");

                    b.HasIndex("UserId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_ai_logs_user_created");

                    b.ToTable("ai_recognition_logs", (string)null);
                });

            modelBuilder.Entity("FoodMate.Core.Entities.DecisionSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("BudgetMaxCents")
                        .HasColumnType("integer")
                        .HasColumnName("budget_max_cents");

                    b.Property<int?>("BudgetMinCents")
                        .HasColumnType("integer")
                        .HasColumnName("budget_min_cents");

                    b.Property<int>("CandidateCount")
                        .HasColumnType("integer")
                        .HasColumnName("candidate_count");

                    b.Property<string>("Candidates")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("candidates");

                    b.Property<DateTimeOffset?>("ChosenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("chosen_at");

                    b.Property<Guid?>("ChosenDishId")
                        .HasColumnType("uuid")
                        .HasColumnName("chosen_dish_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<short>("DiningMode")
                        .HasColumnType("smallint")
                        .HasColumnName("dining_mode");

                    b.Property<int>("ElapsedMs")
                        .HasColumnType("integer")
                        .HasColumnName("elapsed_ms");

                    b.Property<string>("EngineVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("engine_version");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("latitude");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("longitude");

                    b.Property<short>("MealType")
                        .HasColumnType("smallint")
                        .HasColumnName("meal_type");

                    b.Property<string>("MoodTags")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mood_tags");

                    b.Property<short>("PartySize")
                        .HasColumnType("smallint")
                        .HasColumnName("party_size");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Weather")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("weather");

                    b.HasKey("Id");

                    b.HasIndex("ChosenDishId");

                    b.HasIndex("UserId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_decision_sessions_user_created");

                    b.ToTable("decision_sessions", (string)null);
                });

            modelBuilder.Entity("FoodMate.Core.Entities.Dish", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Aliases")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("aliases");

                    b.Property<int?>("Calories")
                        .HasColumnType("integer")
                        .HasColumnName("calories");

                    b.Property<short>("Category")
                        .HasColumnType("smallint")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<short>("Cuisine")
                        .HasColumnType("smallint")
                        .HasColumnName("cuisine");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("image_url");

                    b.Property<string>("Ingredients")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ingredients");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsBuiltin")
                        .HasColumnType("boolean")
                        .HasColumnName("is_builtin");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<short>("MealTimes")
                        .HasColumnType("smallint")
                        .HasColumnName("meal_times");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("name");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<int>("Popularity")
                        .HasColumnType("integer")
                        .HasColumnName("popularity");

                    b.Property<int?>("PriceMaxCents")
                        .HasColumnType("integer")
                        .HasColumnName("price_max_cents");

                    b.Property<int?>("PriceMinCents")
                        .HasColumnType("integer")
                        .HasColumnName("price_min_cents");

                    b.Property<short>("Seasons")
                        .HasColumnType("smallint")
                        .HasColumnName("seasons");

                    b.Property<short>("SpicyLevel")
                        .HasColumnType("smallint")
                        .HasColumnName("spicy_level");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tags");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_dishes_name");

                    b.HasIndex("OwnerUserId")
                        .HasDatabaseName("ix_dishes_owner")
                        .HasFilter("owner_user_id IS NOT NULL");

                    b.HasIndex("Popularity")
                        .IsDescending()
                        .HasDatabaseName("ix_dishes_popularity")
                        .HasFilter("is_active AND NOT is_deleted");

                    b.HasIndex("IsActive", "IsDeleted", "Cuisine", "Category")
                        .HasDatabaseName("ix_dishes_candidates");

                    b.ToTable("dishes", null, t =>
                        {
                            t.HasCheckConstraint("ck_dishes_spicy_range", "spicy_level BETWEEN 0 AND 5");
                        });
                });

            modelBuilder.Entity("FoodMate.Core.Entities.MealRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AiRecognitionLogId")
                        .HasColumnType("uuid")
                        .HasColumnName("ai_recognition_log_id");

                    b.Property<int?>("Calories")
                        .HasColumnType("integer")
                        .HasColumnName("calories");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("DecisionSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("decision_session_id");

                    b.Property<short>("DiningMode")
                        .HasColumnType("smallint")
                        .HasColumnName("dining_mode");

                    b.Property<Guid?>("DishId")
                        .HasColumnType("uuid")
                        .HasColumnName("dish_id");

                    b.Property<string>("DishName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("dish_name");

                    b.Property<string>("DishSnapshot")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dish_snapshot");

                    b.Property<DateTimeOffset>("EatenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("eaten_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<short>("MealType")
                        .HasColumnType("smallint")
                        .HasColumnName("meal_type");

                    b.Property<string>("Note")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("note");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("photo_url");

                    b.Property<short?>("Rating")
                        .HasColumnType("smallint")
                        .HasColumnName("rating");

                    b.Property<double>("Servings")
                        .HasColumnType("double precision")
                        .HasColumnName("servings");

                    b.Property<short>("Source")
                        .HasColumnType("smallint")
                        .HasColumnName("source");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<bool?>("WouldEatAgain")
                        .HasColumnType("boolean")
                        .HasColumnName("would_eat_again");

                    b.HasKey("Id");

                    b.HasIndex("AiRecognitionLogId");

                    b.HasIndex("DecisionSessionId");

                    b.HasIndex("DishId");

                    b.HasIndex("UserId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_meal_records_user_created")
                        .HasFilter("NOT is_deleted");

                    b.HasIndex("UserId", "EatenAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_meal_records_pending_rating")
                        .HasFilter("rating IS NULL AND NOT is_deleted");

                    b.HasIndex("UserId", "DishId", "EatenAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_meal_records_user_dish")
                        .HasFilter("NOT is_deleted");

                    b.ToTable("meal_records", null, t =>
                        {
                            t.HasCheckConstraint("ck_meal_records_rating", "rating IS NULL OR rating BETWEEN 1 AND 5");

                            t.HasCheckConstraint("ck_meal_records_servings", "servings > 0 AND servings <= 10");
                        });
                });

            modelBuilder.Entity("FoodMate.Core.Entities.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<short>("CookMinutes")
                        .HasColumnType("smallint")
                        .HasColumnName("cook_minutes");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<short>("Difficulty")
                        .HasColumnType("smallint")
                        .HasColumnName("difficulty");

                    b.Property<Guid>("DishId")
                        .HasColumnType("uuid")
                        .HasColumnName("dish_id");

                    b.Property<short>("Servings")
                        .HasColumnType("smallint")
                        .HasColumnName("servings");

                    b.Property<string>("Steps")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("steps");

                    b.Property<string>("Tips")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("tips");

                    b.HasKey("Id");

                    b.HasIndex("CookMinutes")
                        .HasDatabaseName("ix_recipes_cook_minutes");

                    b.HasIndex("DishId")
                        .IsUnique()
                        .HasDatabaseName("ux_recipes_dish_id");

                    b.ToTable("recipes", null, t =>
                        {
                            t.HasCheckConstraint("ck_recipes_difficulty", "difficulty BETWEEN 1 AND 3");
                        });
                });

            modelBuilder.Entity("FoodMate.Core.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<short>("Platform")
                        .HasColumnType("smallint")
                        .HasColumnName("platform");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_token_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_refresh_tokens_expires");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_refresh_tokens_hash");

                    b.HasIndex("UserId", "ExpiresAt")
                        .HasDatabaseName("ix_refresh_tokens_user_expires");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("FoodMate.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("avatar_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("Nickname")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nickname");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("FoodMate.Core.Entities.UserCuisineStat", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<short>("Cuisine")
                        .HasColumnType("smallint")
                        .HasColumnName("cuisine");

                    b.Property<int>("EatCountTotal")
                        .HasColumnType("integer")
                        .HasColumnName("eat_count_total");

                    b.Property<DateTimeOffset?>("LastEatenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_eaten_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId", "Cuisine");

                    b.HasIndex("UserId", "LastEatenAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_user_cuisine_stats_last_eaten");

                    b.ToTable("user_cuisine_stats", (string)null);
                });

            modelBuilder.Entity("FoodMate.Core.Entities.UserDishStat", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("DishId")
                        .HasColumnType("uuid")
                        .HasColumnName("dish_id");

                    b.Property<int>("EatCount")
                        .HasColumnType("integer")
                        .HasColumnName("eat_count");

                    b.Property<DateTimeOffset?>("LastEatenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_eaten_at");

                    b.Property<int>("RatingCount")
                        .HasColumnType("integer")
                        .HasColumnName("rating_count");

                    b.Property<int>("RatingSum")
                        .HasColumnType("integer")
                        .HasColumnName("rating_sum");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("WouldEatAgainCount")
                        .HasColumnType("integer")
                        .HasColumnName("would_eat_again_count");

                    b.Property<int>("WouldNotEatAgainCount")
                        .HasColumnType("integer")
                        .HasColumnName("would_not_eat_again_count");

                    b.HasKey("UserId", "DishId");

                    b.HasIndex("DishId");

                    b.HasIndex("UserId", "LastEatenAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_user_dish_stats_last_eaten");

                    b.ToTable("user_dish_stats", (string)null);
                });

            modelBuilder.Entity("FoodMate.Core.Entities.UserIdentity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("OpenId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("open_id");

                    b.Property<short>("Platform")
                        .HasColumnType("smallint")
                        .HasColumnName("platform");

                    b.Property<string>("UnionId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("union_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UnionId")
                        .HasDatabaseName("ix_user_identities_union_id")
                        .HasFilter("union_id IS NOT NULL");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_identities_user_id");

                    b.HasIndex("Platform", "OpenId")
                        .IsUnique()
                        .HasDatabaseName("ux_user_identities_platform_openid");

                    b.ToTable("user_identities", (string)null);
                });

            modelBuilder.Entity("FoodMate.Core.Entities.UserPreference", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("AvoidIngredients")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("avoid_ingredients");

                    b.Property<int>("BudgetMaxCents")
                        .HasColumnType("integer")
                        .HasColumnName("budget_max_cents");

                    b.Property<int>("BudgetMinCents")
                        .HasColumnType("integer")
                        .HasColumnName("budget_min_cents");

                    b.Property<string>("DiningModeWeights")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dining_mode_weights");

                    b.Property<int>("MaxDistanceM")
                        .HasColumnType("integer")
                        .HasColumnName("max_distance_m");

                    b.Property<bool>("OnboardingCompleted")
                        .HasColumnType("boolean")
                        .HasColumnName("onboarding_completed");

                    b.Property<string>("PreferredCuisines")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("preferred_cuisines");

                    b.Property<short>("SpicyLevel")
                        .HasColumnType("smallint")
                        .HasColumnName("spicy_level");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId");

                    b.ToTable("user_preferences", null, t =>
                        {
                            t.HasCheckConstraint("ck_user_preferences_budget_range", "budget_min_cents >= 0 AND budget_max_cents >= budget_min_cents");

                            t.HasCheckConstraint("ck_user_preferences_spicy_range", "spicy_level BETWEEN 0 AND 5");
                        });
                });

            modelBuilder.Entity("FoodMate.Core.Entities.AiRecognitionLog", b =>
                {
                    b.HasOne("FoodMate.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FoodMate.Core.Entities.DecisionSession", b =>
                {
                    b.HasOne("FoodMate.Core.Entities.Dish", null)
                        .WithMany()
                        .HasForeignKey("ChosenDishId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FoodMate.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FoodMate.Core.Entities.Dish", b =>
                {
                    b.HasOne("FoodMate.Core.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("FoodMate.Core.Entities.MealRecord", b =>
                {
                    b.HasOne("FoodMate.Core.Entities.AiRecognitionLog", "AiRecognitionLog")
                        .WithMany()
                        .HasForeignKey("AiRecognitionLogId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FoodMate.Core.Entities.DecisionSession", "DecisionSession")
                        .WithMany()
                        .HasForeignKey("DecisionSessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FoodMate.Core.Entities.Dish", "Dish")
                        .WithMany()
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FoodMate.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AiRecognitionLog");

                    b.Navigation("DecisionSession");

                    b.Navigation("Dish");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FoodMate.Core.Entities.Recipe", b =>
                {
                    b.HasOne("FoodMate.Core.Entities.Dish", "Dish")
                        .WithOne("Recipe")
                        .HasForeignKey("FoodMate.Core.Entities.Recipe", "DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dish");
                });

            modelBuilder.Entity("FoodMate.Core.Entities.RefreshToken", b =>
                {
                    b.HasOne("FoodMate.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FoodMate.Core.Entities.UserCuisineStat", b =>
                {
                    b.HasOne("FoodMate.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FoodMate.Core.Entities.UserDishStat", b =>
                {
                    b.HasOne("FoodMate.Core.Entities.Dish", "Dish")
                        .WithMany()
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodMate.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dish");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FoodMate.Core.Entities.UserIdentity", b =>
                {
                    b.HasOne("FoodMate.Core.Entities.User", "User")
                        .WithMany("Identities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FoodMate.Core.Entities.UserPreference", b =>
                {
                    b.HasOne("FoodMate.Core.Entities.User", "User")
                        .WithOne("Preference")
                        .HasForeignKey("FoodMate.Core.Entities.UserPreference", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FoodMate.Core.Entities.Dish", b =>
                {
                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("FoodMate.Core.Entities.User", b =>
                {
                    b.Navigation("Identities");

                    b.Navigation("Preference");
                });
#pragma warning restore 612, 618
        }
    }
}
